### ISSUE TITLE
Network settings not created for all build artifacts

### ISSUE THREAD

**Issue by bweick** [RequestNetwork/Request_SmartContracts#5]
### What was wrong?
When running the migration files, the build artifacts for `RequestEthereum`, `RequestSynchroneExtensionEscrow`, and `RequestBurnManagerSimple` are not created with network settings thus making it hard to develop efficiently in the truffle environment (for example: `contractName.deployed()` can't be called on the above contracts).

### How can it be fixed?
I rewrote the `2_deploy_contracts.js` file [here](https://github.com/bweick/Request_SmartContracts/blob/rewrite_migration_2/migrations/2_deploy_contracts.js) and propose something similar (or I can just merge that branch). This allows access to all deployed contracts within the truffle environment making it easier for developers to build and test potential Request Extensions.

**Comment by vrolland** [comment]
The artifacts management will be modified in the next weeks.
Feel free to make PR anyway in case.

**Comment by bweick** [comment]
Cool. Done.

**Comment by vrolland** [comment]
perfect, merged. Thank you bweick.
